version: '3.1'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
    environment:
      NODE_ENV: development
      DATABASE_URL: $DATABASE_URL
      JWT_SECRET: $JWT_SECRET
      COOKIE_SECRET: $COOKIE_SECRET


      LOKI_URL: $LOKI_URL
      LOKI_USERNAME: $LOKI_USERNAME
      LOKI_TOKEN: $LOKI_TOKEN

